name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    
    - name: Restore Dependencies
      run: dotnet restore Ambev.DeveloperEvaluation.sln

    - name: Build Solution
      run: dotnet build Ambev.DeveloperEvaluation.sln --configuration Release --no-restore

    - name: Run Tests with Code Coverage
      run: |
        dotnet test Ambev.DeveloperEvaluation.sln --no-restore --verbosity normal \
        /p:CollectCoverage=true \
        /p:CoverletOutputFormat=cobertura \
        /p:CoverletOutput=./TestResults/coverage.cobertura.xml \
        /p:Exclude="[*]*.Program%2c[*]*.Startup%2c[*]*.Migrations.*"